---
title: "People"
toc-depth: 2
---

# Group Lead

## Kyle P Messier, PhD {#KPM}

![Kyle P Messier is a Stadtman Tenure-Track Investigator at the National Institute of Environmental Health Sciences (NIEHS) in the Division of Translational Toxicology (DTT). He leads the Spatiotemporal Exposures and Toxicology group, {SET}grp, within the Predictive Toxicology Branch. He also holds a joint appointment with the National Institute of Minority Health and Health Disparities (NIMHD) in Bethesda, Maryland and a secondary appointment in the NIEHS Biostatistics and Computational Biology Branch. Messier received a B.S. in Environmental Studies from the University of North Carolina at Asheville and a M.S. and Ph.D. from the University of North Carolina at Chapel Hill.](images/KPM-headshot-Oct2023.jpg){width="30%"}

# Postdoctoral Fellows

It's no secret that the engine driving cutting edge research across the world is postdoctoral fellows. The SET group has many talented postdoctoral fellows with a variety of backgrounds including spatial statistics, machine learning, epidemiology, atmospheric sciences, and geography.

Current fellows, alphabetically by last name:

## Mariana Alifa Kassien {#MAK}

![Dr. Mariana Alifa Kassien research interets lie at the nexus of environment and society. She has experience in air quality modeling, health effect quantification, uncertainty assessment, and space-time geospatial data resources. Currently, Dr. Alifa Kassien is working on novel physics informed neural networks for atmospheric dispersion models of data sparse chemicals. She also has interest in science education and outreach where she is working on developing knowledge and dissemination materials on climate change and health effects.](images/MAK-headshot-Oct2023.jpg){width="20%"}

## Ranadeep Daw {#RD}

![Dr. Ranadeep Daw has comprehensive training throughout my bachelor's, master's, and doctoral studies in Statistics, both methodological and applied areas of Statistics. He has experience in methodologies for spatiotemporal data aggregation and low-rank scalable modeling, applying these in the exploration of diverse datasets from satellite, survey, environmental, and meteorological data sources. Currently, he is developing a novel spatially explicit tree and Gaussian process based boosting model aimed at making interpretable models with predictive performance competitive with advanced machine learning models.](images/RD-Headshot-Oct2023.jpg){width="20%"}

## Eva Marques {#ESM}

![Dr. Eva Marques is an applied geostatistician with a primary focus in urban climatology. She uses Bayesian and machine learning methods to predict climate exposures such as the urban heat island effect. She holds a MS in Applied Math from the National Institute of Applied Sciences (INSA) in Toulouse, France, and a PhD in Urban Climatology from the National Meteorlogical Center in Toulouse, France.](images/ESM-headshot-Oct2023.jpg){width="21%"}

## [Insang Song](https://sigmafelix.wixsite.com/mysite/ "Postdoctoral Fellow") {#IS}

![Dr. Insang Song is spatial scientist interested in the impact of socioenvironmental nexus on human health. He has a BA and MS in Geography from Seoul National University in Korea and PhD in Geography from the University of Oregon. His current research projects include developing scalable GIS software for climate and health, hybrid air pollution modeling, and mental health impacts from climate related exposures.](images/IS-Headshot-Oct2023.jpg){width="20%"}

## Daniel Zilber {#DZ}

![Dr. Zilber is a postdoctoral fellow working on novel statistical methods to predict chemical mixtures. As a card-carrying Bayesian he has broad interest in Bayesian modeling in Biostatistics, kernel methods and stochastic processes, deep learning vs statistics vs quantum probability. He has a BS in Math from UNC Chapel Hill, a MS in Operations Research from Stanford University, and PhD in Statistics from Texas A&M University.](images/DZ-Headshot-Oct2023.jpg){width="20%"}

# Data Analyst

## Mitchell Manware {#MM}

![Mr. Mitchell Manware holds a BS in Business and Health Care Management from the University of Connecticut and a MPH from the Yale School of Public Health. He has experience in geospatial data analysis, public health data visualization, and policy-oriented writing. Currently, he is a geospatial analyst in climate change and health funded by the Climate and Health Outcomes Research Data Systems (CHORDS) project where is developing geospatial tools and educational resources focused on environment, climate, and health. ](images/manware_headshot.jpeg){width="20%"}

# Former Members {#FormerMembers}

1.  [Kristin Eccles](https://kristineccles.wordpress.com/), Postdoctoral Fellow, Now at Health Canada

2.  [Melissa Lowe](https://www.linkedin.com/in/melissa-lowe-1a62a8b3/), Postbaccalaureate Fellow, Now at Duke Cancer Institute

3.  Taylor A Potter, Postbaccalaureate Fellow, Now in medical school at Meherry Medical College
